### ISSUE TITLE
wdfs copy/create not working

### ISSUE THREAD

**Issue by waitman** [jmesmon/wdfs#1]
After mounting remote WebDav host to local filesystem, it is not possible to copy/create files on the mounted system.

```
# cp /boo1.txt boo/
cp: boo/boo1.txt: Invalid argument

# cp /boo1.txt .
cp: ./boo1.txt: Invalid argument

"PROPFIND /dav/waitman/boo/boo1.txt HTTP/1.1" 404 302 "-" "wdfs/1.4.2 neon/0.30.1"
"PROPFIND /dav/waitman/boo1.txt HTTP/1.1" 404 302 "-" "wdfs/1.4.2 neon/0.30.1"
```

It seems the 404 error from PROPFIND is causing wdfs to return error and abort the operation.

This solution seems to work: implement wdfs_create() function. Which basically calls mknod() and open()

https://github.com/waitman/wdfs/blob/master/src/wdfs-main.c

```
static int wdfs_create(const char *localpath, mode_t mode, struct fuse_file_info *fi)
{

    int ret;
    dev_t rdev;
    rdev = (dev_t)0;

    ret = wdfs_mknod(localpath,mode,rdev);
    if (ret!=0)
    {
        return ret;
    }
    ret = wdfs_open(localpath, fi);
    return ret;

}

```

**Comment by codyps** [comment]
That makes sense. I'm not using this actively anymore, but if you open a pull request, I'd be happy to merge it.

**Comment by waitman** [comment]
thanks, I cleaned up things a bit and opened a pull request. Thanks

**Comment by codyps** [comment]
#2 fixed this a long time ago
